export type RiskLevel = "High" | "Medium" | "Low";
export type CollarType = "White Collar" | "Blue Collar";
export type ValidationStatus =
  | "Validated"
  | "Need Manual Check"
  | "Industry Dependent"
  | "Low Confidence";

export type JobImpact = {
  id: string;
  jobTitle: string;
  jobCategory: string;
  collarType: CollarType;
  mainTasks: string;
  aiExposureLevel: RiskLevel;
  replacementRiskLevel: RiskLevel;
  reason: string;
  humanRelevantSkills: string;
  aiToolsImpact: string;
  validationNote: string;
  recommendedAction: string;
  confidenceScore: number;
  validationStatus: ValidationStatus;
  sourceReference: string;
  createdBy?: string | null;
};

export const jobs: JobImpact[] = [
  {
    id: "1",
    jobTitle: "Data Entry Clerk",
    jobCategory: "Administration",
    collarType: "White Collar",
    mainTasks:
      "Input data, validate records, update spreadsheets, and maintain databases.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason:
      "Highly repetitive, digital, and rule-based work that is straightforward to automate with AI and workflow tools.",
    humanRelevantSkills: "Accuracy checking, domain knowledge, exception handling.",
    aiToolsImpact: "ChatGPT, OCR tools, spreadsheet automation, RPA.",
    validationNote: "Needs manual check for industry-specific workflows.",
    recommendedAction: "Automate routine tasks",
    confidenceScore: 88,
    validationStatus: "Validated",
    sourceReference: "ILO/WEF-inspired classification",
  },
  {
    id: "2",
    jobTitle: "Customer Service Agent",
    jobCategory: "Service",
    collarType: "White Collar",
    mainTasks:
      "Respond to customer questions, handle complaints, and provide product information.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason:
      "Many standard responses are automatable, but complex complaints and emotional situations still require human judgment.",
    humanRelevantSkills:
      "Empathy, negotiation, escalation handling, emotional intelligence.",
    aiToolsImpact: "AI chatbots, CRM assistants, call summarization.",
    validationNote: "Risk depends on industry and customer complexity.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 74,
    validationStatus: "Industry Dependent",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "3",
    jobTitle: "Nurse",
    jobCategory: "Healthcare",
    collarType: "White Collar",
    mainTasks:
      "Provide patient care, monitor conditions, assist doctors, and communicate with families.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Low",
    reason:
      "AI can assist documentation and monitoring, but direct patient care requires human presence, empathy, and clinical accountability.",
    humanRelevantSkills: "Patient care, empathy, clinical judgment, communication.",
    aiToolsImpact: "Clinical documentation assistants, diagnostic support tools.",
    validationNote: "AI supports the role but does not replace core responsibility.",
    recommendedAction: "Prioritize human judgment",
    confidenceScore: 90,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "4",
    jobTitle: "Content Writer (General)",
    jobCategory: "Media",
    collarType: "White Collar",
    mainTasks:
      "Write blog posts, product descriptions, and social media captions.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason:
      "Generic writing tasks are easily replicated by generative AI at scale.",
    humanRelevantSkills: "Editorial judgment, brand voice, original research.",
    aiToolsImpact: "ChatGPT, Jasper, Copy.ai.",
    validationNote: "Specialized or investigative writing remains resilient.",
    recommendedAction: "Reskill into AI supervision",
    confidenceScore: 82,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "5",
    jobTitle: "Telemarketer",
    jobCategory: "Sales",
    collarType: "White Collar",
    mainTasks: "Cold call leads, pitch products, log call outcomes.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason:
      "Scripted, high-volume outreach can be handled by AI voice agents and automated dialers.",
    humanRelevantSkills: "Relationship building, complex objection handling.",
    aiToolsImpact: "AI voice agents, auto-dialers, LLM script generators.",
    validationNote: "High-value B2B outreach still needs human closers.",
    recommendedAction: "Automate routine tasks",
    confidenceScore: 85,
    validationStatus: "Validated",
    sourceReference: "WEF-inspired classification",
  },
  {
    id: "6",
    jobTitle: "Transcriptionist",
    jobCategory: "Administration",
    collarType: "White Collar",
    mainTasks: "Convert audio recordings into written text.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason: "Modern speech-to-text models handle most transcription accurately.",
    humanRelevantSkills: "Legal/medical terminology, quality assurance.",
    aiToolsImpact: "Whisper, Otter.ai, Rev AI.",
    validationNote: "Specialized domains still require human QA.",
    recommendedAction: "Redesign workflow around AI tools",
    confidenceScore: 87,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "7",
    jobTitle: "Graphic Designer",
    jobCategory: "Media",
    collarType: "White Collar",
    mainTasks: "Create visual assets, illustrations, and layout designs.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason:
      "Generative image tools accelerate ideation, but brand and art direction still need designers.",
    humanRelevantSkills: "Art direction, brand consistency, creative critique.",
    aiToolsImpact: "Midjourney, Adobe Firefly, Canva AI.",
    validationNote: "Senior/creative direction roles are more resilient.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 70,
    validationStatus: "Industry Dependent",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "8",
    jobTitle: "Software Engineer",
    jobCategory: "Technology",
    collarType: "White Collar",
    mainTasks: "Design, build, and maintain software systems.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason:
      "AI assistants boost productivity dramatically, but system design and accountability require humans.",
    humanRelevantSkills: "System design, debugging, cross-team communication.",
    aiToolsImpact: "GitHub Copilot, Cursor, code review assistants.",
    validationNote: "Junior roles more affected than senior.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 78,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "9",
    jobTitle: "Accountant",
    jobCategory: "Finance",
    collarType: "White Collar",
    mainTasks: "Prepare financial records, reconciliations, and tax filings.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason:
      "Bookkeeping is heavily automatable; audit judgment and advisory work remain human.",
    humanRelevantSkills: "Advisory, ethics, complex regulatory judgment.",
    aiToolsImpact: "AI bookkeeping, Xero, QuickBooks copilots.",
    validationNote: "CPA-level judgment is safer than transactional work.",
    recommendedAction: "Reskill into AI supervision",
    confidenceScore: 76,
    validationStatus: "Validated",
    sourceReference: "WEF-inspired classification",
  },
  {
    id: "10",
    jobTitle: "Paralegal",
    jobCategory: "Legal",
    collarType: "White Collar",
    mainTasks: "Draft documents, research case law, and manage case files.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason: "Legal research and drafting are increasingly AI-assisted.",
    humanRelevantSkills: "Client interaction, jurisdictional judgment.",
    aiToolsImpact: "Harvey AI, Casetext CoCounsel.",
    validationNote: "Specialized practice areas remain safer.",
    recommendedAction: "Redesign workflow around AI tools",
    confidenceScore: 72,
    validationStatus: "Industry Dependent",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "11",
    jobTitle: "Electrician",
    jobCategory: "Skilled Trades",
    collarType: "Blue Collar",
    mainTasks:
      "Install and repair electrical systems in buildings and industrial sites.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason: "Physical, on-site, and safety-critical work is hard to automate.",
    humanRelevantSkills: "Manual dexterity, safety judgment, field problem-solving.",
    aiToolsImpact: "Diagnostic apps, scheduling tools.",
    validationNote: "AI mostly augments planning, not fieldwork.",
    recommendedAction: "Use AI only as support tool",
    confidenceScore: 92,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "12",
    jobTitle: "Plumber",
    jobCategory: "Skilled Trades",
    collarType: "Blue Collar",
    mainTasks:
      "Install and maintain piping systems, fix leaks, and troubleshoot on-site.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason: "Physical inspection and repair in unpredictable environments.",
    humanRelevantSkills: "Manual dexterity, judgment in confined spaces.",
    aiToolsImpact: "Booking/dispatch platforms.",
    validationNote: "Low risk short and medium term.",
    recommendedAction: "Monitor industry-specific change",
    confidenceScore: 91,
    validationStatus: "Validated",
    sourceReference: "ILO-inspired classification",
  },
  {
    id: "13",
    jobTitle: "Warehouse Worker",
    jobCategory: "Logistics",
    collarType: "Blue Collar",
    mainTasks: "Pick, pack, and move goods across a warehouse.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Medium",
    reason:
      "Robotics and warehouse automation are advancing, but many facilities still rely on human labor.",
    humanRelevantSkills: "Adaptability, exception handling.",
    aiToolsImpact: "Robotics, warehouse management systems.",
    validationNote: "Depends on capex and facility maturity.",
    recommendedAction: "Monitor industry-specific change",
    confidenceScore: 68,
    validationStatus: "Industry Dependent",
    sourceReference: "WEF-inspired classification",
  },
  {
    id: "14",
    jobTitle: "Truck Driver",
    jobCategory: "Logistics",
    collarType: "Blue Collar",
    mainTasks: "Transport goods over long or short distances.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Medium",
    reason:
      "Autonomous trucking is progressing but regulatory and operational barriers remain.",
    humanRelevantSkills: "Route judgment, cargo handling, customer interaction.",
    aiToolsImpact: "ADAS, route optimization, autonomous pilots.",
    validationNote: "Long tail before full automation is realistic.",
    recommendedAction: "Reskill into AI supervision",
    confidenceScore: 65,
    validationStatus: "Industry Dependent",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "15",
    jobTitle: "Teacher",
    jobCategory: "Education",
    collarType: "White Collar",
    mainTasks: "Design lessons, teach students, and assess learning outcomes.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Low",
    reason:
      "Teaching involves mentorship, motivation, and social dynamics AI cannot replicate.",
    humanRelevantSkills: "Mentorship, empathy, classroom management.",
    aiToolsImpact: "Lesson planners, grading assistants, tutors.",
    validationNote: "AI augments; does not replace teacher-student relationship.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 84,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "16",
    jobTitle: "Field Technician",
    jobCategory: "Skilled Trades",
    collarType: "Blue Collar",
    mainTasks: "Install, service, and repair equipment on site.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason: "Requires physical presence and situational judgment on site.",
    humanRelevantSkills: "Diagnosis, manual dexterity, customer interaction.",
    aiToolsImpact: "AR-assisted repair, ticketing systems.",
    validationNote: "Low near-term risk.",
    recommendedAction: "Use AI only as support tool",
    confidenceScore: 89,
    validationStatus: "Validated",
    sourceReference: "ILO-inspired classification",
  },
  {
    id: "17",
    jobTitle: "Marketing Manager",
    jobCategory: "Marketing",
    collarType: "White Collar",
    mainTasks: "Plan campaigns, manage budgets, and coordinate teams.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Low",
    reason: "Strategy, stakeholder alignment, and brand judgment stay human.",
    humanRelevantSkills: "Strategy, leadership, stakeholder management.",
    aiToolsImpact: "AI copywriting, analytics, campaign generators.",
    validationNote: "Operational marketers more exposed than strategists.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 77,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "18",
    jobTitle: "HR Recruiter",
    jobCategory: "Human Resources",
    collarType: "White Collar",
    mainTasks: "Source candidates, screen resumes, coordinate interviews.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason: "Sourcing and screening automate well; final judgment stays human.",
    humanRelevantSkills: "Interviewing, candidate empathy, hiring judgment.",
    aiToolsImpact: "AI sourcing, resume parsing, scheduling bots.",
    validationNote: "Bias risks require human oversight.",
    recommendedAction: "Redesign workflow around AI tools",
    confidenceScore: 74,
    validationStatus: "Need Manual Check",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "19",
    jobTitle: "Financial Analyst",
    jobCategory: "Finance",
    collarType: "White Collar",
    mainTasks: "Model financials, prepare reports, and support decisions.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason: "Modeling and reporting speed up with AI; interpretation stays human.",
    humanRelevantSkills: "Business judgment, storytelling with data.",
    aiToolsImpact: "Copilot for Excel, AI research assistants.",
    validationNote: "Senior analysts more resilient.",
    recommendedAction: "Reskill into AI supervision",
    confidenceScore: 75,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "20",
    jobTitle: "Chef",
    jobCategory: "Hospitality",
    collarType: "Blue Collar",
    mainTasks: "Design menus, cook meals, and manage kitchen operations.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason:
      "Creativity, taste, and hands-on kitchen work are hard to automate at scale.",
    humanRelevantSkills: "Palate, creativity, team leadership.",
    aiToolsImpact: "Recipe suggestion, inventory tools.",
    validationNote: "QSR back-of-house may see more automation.",
    recommendedAction: "Use AI only as support tool",
    confidenceScore: 86,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "21",
    jobTitle: "Retail Cashier",
    jobCategory: "Retail",
    collarType: "Blue Collar",
    mainTasks: "Process transactions, handle payments, and assist customers.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason: "Self-checkout and cashierless stores replace many transactions.",
    humanRelevantSkills: "Customer support, exception handling.",
    aiToolsImpact: "Self-checkout, computer vision checkout.",
    validationNote: "Some segments retain cashiers for service reasons.",
    recommendedAction: "Reskill into AI supervision",
    confidenceScore: 80,
    validationStatus: "Validated",
    sourceReference: "WEF-inspired classification",
  },
  {
    id: "22",
    jobTitle: "Translator",
    jobCategory: "Media",
    collarType: "White Collar",
    mainTasks: "Translate documents and localize content.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason: "Machine translation now handles most non-critical content.",
    humanRelevantSkills: "Cultural nuance, legal/medical accuracy.",
    aiToolsImpact: "DeepL, GPT-based translators.",
    validationNote: "Specialized translators still needed.",
    recommendedAction: "Redesign workflow around AI tools",
    confidenceScore: 83,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "23",
    jobTitle: "Journalist",
    jobCategory: "Media",
    collarType: "White Collar",
    mainTasks: "Investigate stories, interview sources, and publish articles.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Medium",
    reason:
      "AI drafts routine news; investigative and source-based journalism stays human.",
    humanRelevantSkills: "Source cultivation, investigative judgment, ethics.",
    aiToolsImpact: "Draft assistants, transcription, research tools.",
    validationNote: "Beat and investigative reporters more resilient.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 69,
    validationStatus: "Industry Dependent",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "24",
    jobTitle: "Radiologist",
    jobCategory: "Healthcare",
    collarType: "White Collar",
    mainTasks: "Interpret medical imaging and support diagnoses.",
    aiExposureLevel: "High",
    replacementRiskLevel: "Medium",
    reason: "AI reads images fast; final diagnosis and accountability stay human.",
    humanRelevantSkills: "Clinical judgment, patient communication.",
    aiToolsImpact: "Radiology AI, computer-aided detection.",
    validationNote: "Workflows augmented, not replaced.",
    recommendedAction: "Reskill into AI supervision",
    confidenceScore: 72,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "25",
    jobTitle: "Construction Worker",
    jobCategory: "Construction",
    collarType: "Blue Collar",
    mainTasks: "Build structures on-site, operate tools and equipment.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason: "Physical, site-specific work is hard to automate broadly.",
    humanRelevantSkills: "Craftsmanship, safety, teamwork.",
    aiToolsImpact: "Planning tools, safety monitoring.",
    validationNote: "Prefab may shift some roles.",
    recommendedAction: "Monitor industry-specific change",
    confidenceScore: 88,
    validationStatus: "Validated",
    sourceReference: "ILO-inspired classification",
  },
  {
    id: "26",
    jobTitle: "Social Worker",
    jobCategory: "Social Services",
    collarType: "White Collar",
    mainTasks: "Support vulnerable individuals and coordinate services.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason: "Deep empathy and relationship work AI cannot replace.",
    humanRelevantSkills: "Empathy, ethical judgment, community trust.",
    aiToolsImpact: "Case management tools, documentation aids.",
    validationNote: "AI supports paperwork; not the core role.",
    recommendedAction: "Prioritize human judgment",
    confidenceScore: 90,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "27",
    jobTitle: "Basic Admin Assistant",
    jobCategory: "Administration",
    collarType: "White Collar",
    mainTasks: "Schedule meetings, manage inbox, prepare basic documents.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason: "Scheduling and inbox management largely automatable.",
    humanRelevantSkills: "Exception handling, discretion.",
    aiToolsImpact: "AI schedulers, inbox copilots.",
    validationNote: "Executive assistants more resilient.",
    recommendedAction: "Automate routine tasks",
    confidenceScore: 84,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "28",
    jobTitle: "UX Designer",
    jobCategory: "Technology",
    collarType: "White Collar",
    mainTasks: "Research users and design interfaces and flows.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Medium",
    reason: "AI accelerates wireframing but user research and judgment remain.",
    humanRelevantSkills: "User empathy, research synthesis.",
    aiToolsImpact: "Uizard, Figma AI, Galileo.",
    validationNote: "Senior UX more resilient.",
    recommendedAction: "Use AI as productivity assistant",
    confidenceScore: 71,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "29",
    jobTitle: "Delivery Driver",
    jobCategory: "Logistics",
    collarType: "Blue Collar",
    mainTasks: "Deliver parcels and food to customer addresses.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Medium",
    reason:
      "Autonomous delivery still limited; last-mile logistics remains largely human.",
    humanRelevantSkills: "Navigation, customer interaction, adaptability.",
    aiToolsImpact: "Route optimization, delivery robots.",
    validationNote: "Depends on city regulations.",
    recommendedAction: "Monitor industry-specific change",
    confidenceScore: 66,
    validationStatus: "Industry Dependent",
    sourceReference: "Internal workshop dataset",
  },
  {
    id: "30",
    jobTitle: "Therapist",
    jobCategory: "Healthcare",
    collarType: "White Collar",
    mainTasks: "Provide mental health counseling and therapy.",
    aiExposureLevel: "Low",
    replacementRiskLevel: "Low",
    reason: "Therapeutic relationship and accountability are fundamentally human.",
    humanRelevantSkills: "Empathy, active listening, clinical ethics.",
    aiToolsImpact: "Journaling apps, session notes, triage bots.",
    validationNote: "AI supports; not a replacement.",
    recommendedAction: "Prioritize human judgment",
    confidenceScore: 92,
    validationStatus: "Validated",
    sourceReference: "OECD-inspired classification",
  },
  {
    id: "31",
    jobTitle: "Bookkeeper",
    jobCategory: "Finance",
    collarType: "White Collar",
    mainTasks: "Record transactions and maintain ledgers.",
    aiExposureLevel: "High",
    replacementRiskLevel: "High",
    reason: "Rule-based and highly digital; AI accounting tools handle most of it.",
    humanRelevantSkills: "Reconciliation judgment, client communication.",
    aiToolsImpact: "AI accounting, bank feeds, auto-categorization.",
    validationNote: "Advisory roles more resilient.",
    recommendedAction: "Automate routine tasks",
    confidenceScore: 86,
    validationStatus: "Validated",
    sourceReference: "WEF-inspired classification",
  },
  {
    id: "32",
    jobTitle: "Security Guard",
    jobCategory: "Security",
    collarType: "Blue Collar",
    mainTasks: "Patrol premises, monitor cameras, and respond to incidents.",
    aiExposureLevel: "Medium",
    replacementRiskLevel: "Low",
    reason:
      "AI cameras assist monitoring but physical presence still required for response.",
    humanRelevantSkills: "Situational judgment, physical response.",
    aiToolsImpact: "Video analytics, anomaly detection.",
    validationNote: "AI augments monitoring only.",
    recommendedAction: "Use AI only as support tool",
    confidenceScore: 78,
    validationStatus: "Validated",
    sourceReference: "Internal workshop dataset",
  },
];
